resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: External-CI-Token
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - .github
    - '.*.y*ml'
    - '*.md'
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - .github
    - '.*.y*ml'
    - '*.md'
    - LICENSE
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocm-cmake.yml@pipelines_repo
