name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install cmakelang[YAML]
    - name: Run tests
      run: |
        cmake-lint $(find ./test -type f | grep .cmake$) $(find ./share -type f | grep .cmake$)