name: rocm-cmake

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install cget cmakelang[YAML]
    - name: Run linter
      run: |
        cget build -T analyze -DSPHINX_EXECUTABLE=python3
#       python isn't sphinx, but we won't be calling it anyway
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform:
          - ubuntu-24.04
          - windows-2022
        cmake-version:
          - 3.31.0
          - 3.22.1
          - 3.16.3
        compiler:
          - default
          - clang
        # There are problems with nmake and ninja with this version of cmake
        # on windows
        exclude:
          - platform: windows-2022
            cmake-version: 3.16.3
          # clang++ is only tested on windows; linux is already covered by the
          # default compiler
          - platform: ubuntu-24.04
            compiler: clang

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Set up Python 3.10
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: "3.10"
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@710e05536f2b819d5918f51a5de5b392e99bba3c # v1.9
      with:
        cmake-version: ${{ matrix.cmake-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install cget ninja
        python -m pip install -r docs/requirements.txt
    - name: Install Doxygen
      uses: ssciwr/doxygen-install@f13be1686235deee0aeb6cdf56640170691dc96b # v1
      with:
        version: "1.10.0"
    - name: Setup git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Install LLVM/Clang
      if: matrix.compiler == 'clang'
      uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0 # v2
      with:
        version: "20"
        directory: ${{ runner.temp }}/llvm

    - name: Setup clang++
      if: matrix.compiler == 'clang'
      shell: bash
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Cmake version
      run: cmake --version

    - name: Run tests (default generator)
      if: matrix.compiler != 'clang'
      run: cget build --test

    - name: Build docs (default generator)
      if: matrix.compiler != 'clang'
      run: cget build -T doc

    - name: Clean build
      run: |
        cget build -Cy
        cget clean -y

    - name: Run tests (Ninja generator)
      run: cget build --test -DROCM_CMAKE_GENERATOR=Ninja

    - name: Build docs (Ninja generator)
      run: cget build -T doc
